"""Sample direct text extraction and OCR diagnostics for BPC source PDFs.

This tool intentionally defaults to sample mode. Full OCR can be expensive and
must be invoked explicitly with --full after a later-stage decision.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

import fitz
import pytesseract
from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
PDF_DIR = ROOT / "docs" / "source" / "bpc-pdf"
TEXT_DIR = ROOT / "docs" / "source" / "bpc-ocr-text"
OUTPUT_DIR = ROOT / "docs" / "source" / "bpc-ocr-output"
CACHE_DIR = ROOT / "docs" / "source" / "bpc-ocr-cache"
STATS_PATH = OUTPUT_DIR / "bpc-pdf-ocr-stats.json"
DIRECT_TEXT_THRESHOLD = 500
OCR_TEXT_THRESHOLD = 20
OCR_TIMEOUT_SECONDS = 90
KEYWORDS = [
    "Model",
    "Dimension",
    "Member",
    "Hierarchy",
    "Input Schedule",
    "Report",
    "Work Status",
    "Data Manager",
    "Transformation",
    "Conversion",
    "Actual",
    "Budget",
    "Forecast",
    "Data Access",
    "Script Logic",
    "Business Rule",
    "Consolidation",
]


def configure_tesseract() -> str | None:
    """Return the tesseract executable path if it is available."""
    exe = shutil.which("tesseract")
    if exe:
        return exe

    default_path = Path(r"C:\Program Files\Tesseract-OCR\tesseract.exe")
    if default_path.exists():
        pytesseract.pytesseract.tesseract_cmd = str(default_path)
        return str(default_path)

    return None


def normalize_text(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def safe_stem(path: Path) -> str:
    cleaned = re.sub(r"[^\w\u4e00-\u9fff.-]+", "_", path.stem, flags=re.UNICODE)
    return cleaned[:120].strip("_") or "pdf"


def sample_pages(page_count: int) -> list[int]:
    if page_count <= 0:
        return []
    first = range(0, min(5, page_count))
    mid_center = page_count // 2
    middle = range(max(0, mid_center - 2), min(page_count, mid_center + 3))
    last = range(max(0, page_count - 5), page_count)
    return sorted(set(first) | set(middle) | set(last))


def full_pages(page_count: int) -> list[int]:
    return list(range(page_count))


def keyword_hits(text: str) -> dict[str, int]:
    lowered = text.lower()
    return {
        keyword: len(re.findall(re.escape(keyword.lower()), lowered))
        for keyword in KEYWORDS
    }


def render_page_for_ocr(page: fitz.Page) -> Image.Image:
    # 1.5x is deliberately modest: enough for diagnostics without full-OCR cost.
    pix = page.get_pixmap(matrix=fitz.Matrix(1.5, 1.5), alpha=False)
    mode = "RGB" if pix.n < 4 else "RGBA"
    return Image.frombytes(mode, [pix.width, pix.height], pix.samples)


def page_cache_path(pdf_path: Path, page_index: int) -> Path:
    return CACHE_DIR / safe_stem(pdf_path) / f"page-{page_index + 1:04d}.json"


def load_page_cache(path: Path) -> tuple[dict, str, str] | None:
    if not path.exists():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        return payload["record"], payload.get("direct_text", ""), payload.get("ocr_text", "")
    except Exception:
        return None


def write_page_cache(path: Path, record: dict, direct_text: str, ocr_text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "record": record,
        "direct_text": direct_text,
        "ocr_text": ocr_text,
    }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def process_pdf(
    pdf_path: Path,
    pages: list[int],
    tesseract_path: str | None,
    mode_name: str,
    use_cache: bool,
) -> dict:
    direct_effective_pages = 0
    suspected_scan_pages = 0
    ocr_success_pages = 0
    ocr_failed_pages = 0
    sample_total_chars = 0
    keyword_counter: Counter[str] = Counter()
    page_records = []
    output_parts = [
        f"# OCR {mode_name.title()}: {pdf_path.name}",
        "",
        f"This file is generated by tools/extract_bpc_pdf_text.py in {mode_name} mode.",
        "It is an ignored diagnostic cache, not a formal knowledge package.",
        "",
    ]

    with fitz.open(pdf_path) as doc:
        for page_index in pages:
            cache_path = page_cache_path(pdf_path, page_index)
            cached = load_page_cache(cache_path) if use_cache else None
            if cached:
                record, direct_text, ocr_text = cached
                record["from_cache"] = True
            else:
                record = {
                    "page": page_index + 1,
                    "direct_text_chars": 0,
                    "ocr_text_chars": 0,
                    "direct_text_effective": False,
                    "suspected_scan": False,
                    "ocr_status": "not_run",
                    "error": None,
                    "from_cache": False,
                }
                page = doc[page_index]
                direct_text = normalize_text(page.get_text("text"))
                record["direct_text_chars"] = len(direct_text)
                record["direct_text_effective"] = len(direct_text) >= DIRECT_TEXT_THRESHOLD

                ocr_text = ""
                if not record["direct_text_effective"]:
                    record["suspected_scan"] = True
                    if not tesseract_path:
                        record["ocr_status"] = "failed"
                        record["error"] = "tesseract executable not available"
                    else:
                        try:
                            image = render_page_for_ocr(page)
                            ocr_text = normalize_text(
                                pytesseract.image_to_string(
                                    image,
                                    lang="eng",
                                    config="--psm 6",
                                    timeout=OCR_TIMEOUT_SECONDS,
                                )
                            )
                            record["ocr_text_chars"] = len(ocr_text)
                            if len(ocr_text) >= OCR_TEXT_THRESHOLD:
                                record["ocr_status"] = "success"
                            else:
                                record["ocr_status"] = "failed"
                                record["error"] = "ocr output below threshold"
                        except Exception as exc:  # noqa: BLE001 - diagnostics must keep real error
                            record["ocr_status"] = "failed"
                            record["error"] = f"{type(exc).__name__}: {exc}"
                if use_cache:
                    write_page_cache(cache_path, record, direct_text, ocr_text)

            if record["direct_text_effective"]:
                direct_effective_pages += 1
            if record["suspected_scan"]:
                suspected_scan_pages += 1
            if record["ocr_status"] == "success":
                ocr_success_pages += 1
            elif record["ocr_status"] == "failed":
                ocr_failed_pages += 1

            combined = "\n".join(part for part in [direct_text, ocr_text] if part)
            sample_total_chars += len(combined)
            keyword_counter.update(keyword_hits(combined))
            output_parts.extend(
                [
                    f"## Page {page_index + 1}",
                    "",
                    f"- Direct text chars: {record['direct_text_chars']}",
                    f"- OCR status: {record['ocr_status']}",
                    f"- OCR text chars: {record['ocr_text_chars']}",
                    "",
                    "### Direct Text Sample",
                    "",
                    direct_text[:1200] if direct_text else "(none)",
                    "",
                    "### OCR Text Sample",
                    "",
                    ocr_text[:1200] if ocr_text else "(not run or no useful text)",
                    "",
                ]
            )
            page_records.append(record)

        keyword_result = {keyword: keyword_counter.get(keyword, 0) for keyword in KEYWORDS}
        recommend_full_ocr = (
            suspected_scan_pages > 0
            and ocr_success_pages >= max(1, suspected_scan_pages // 2)
        )
        stats = {
            "file_name": pdf_path.name,
            "total_pages": len(doc),
        "processed_pages": len(pages),
        "page_numbers": [page + 1 for page in pages],
            "direct_text_effective_pages": direct_effective_pages,
            "suspected_scan_pages": suspected_scan_pages,
            "ocr_success_pages": ocr_success_pages,
            "ocr_failed_pages": ocr_failed_pages,
            "sample_total_chars": sample_total_chars,
            "keyword_hits": keyword_result,
            "recommend_full_ocr": recommend_full_ocr,
            "page_records": page_records,
        }

    text_path = TEXT_DIR / f"{safe_stem(pdf_path)}.{mode_name}.txt"
    text_path.write_text("\n".join(output_parts), encoding="utf-8")
    stats["sample_text_path"] = str(text_path.relative_to(ROOT))
    return stats


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--sample", action="store_true", help="Process sampled pages only.")
    mode.add_argument("--full", action="store_true", help="Process every page. Expensive.")
    parser.add_argument(
        "--pdf-index",
        type=int,
        help="Process only one 1-based PDF index after sorting by file name.",
    )
    parser.add_argument(
        "--no-cache",
        action="store_true",
        help="Do not read or write page cache files.",
    )
    args = parser.parse_args()

    if not PDF_DIR.exists():
        raise SystemExit(f"PDF directory not found: {PDF_DIR}")

    TEXT_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    CACHE_DIR.mkdir(parents=True, exist_ok=True)

    tesseract_path = configure_tesseract()
    pdfs = sorted(PDF_DIR.glob("*.pdf"))
    if args.pdf_index is not None:
        if args.pdf_index < 1 or args.pdf_index > len(pdfs):
            raise SystemExit(f"--pdf-index must be between 1 and {len(pdfs)}")
        pdfs = [pdfs[args.pdf_index - 1]]
    results = []
    mode_name = "full" if args.full else "sample"

    for pdf_path in pdfs:
        with fitz.open(pdf_path) as doc:
            pages = full_pages(len(doc)) if args.full else sample_pages(len(doc))
        print(f"Processing {pdf_path.name} ({len(pages)} pages)...")
        results.append(process_pdf(pdf_path, pages, tesseract_path, mode_name, not args.no_cache))

    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "mode": mode_name,
        "pdf_dir": str(PDF_DIR.relative_to(ROOT)),
        "tesseract_path": tesseract_path,
        "direct_text_threshold": DIRECT_TEXT_THRESHOLD,
        "ocr_text_threshold": OCR_TEXT_THRESHOLD,
        "keywords": KEYWORDS,
        "pdf_count": len(results),
        "results": results,
    }
    STATS_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote stats: {STATS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
